"""Public contracts and data models for Vision Model Factory."""

from vision_model_factory.contracts.hashing import (
    compute_sha256_bytes,
    compute_sha256_file,
    compute_sha256_str,
    is_valid_sha256,
)
from vision_model_factory.contracts.models import (
    AnnotationRecord,
    CategorySpec,
    ClassMapItem,
    DatasetManifest,
    DatasetRef,
    DecoderSpec,
    EvaluationReport,
    ExperimentSpec,
    FileRef,
    InputSpec,
    ModelManifest,
    OutputSpec,
    ParamsSpec,
    PostprocessSpec,
    PreprocessSpec,
    RunResult,
    SampleRecord,
    TargetSpec,
    TaskSpec,
    TrainerSpec,
)
from vision_model_factory.contracts.validators import (
    ValidationError,
    validate_bbox_coordinates,
    validate_class_map_against_task,
    validate_dataset_package,
    validate_model_package,
    validate_relative_path,
)

__all__ = [
    "AnnotationRecord",
    "CategorySpec",
    "ClassMapItem",
    "DecoderSpec",
    "DatasetManifest",
    "DatasetRef",
    "EvaluationReport",
    "ExperimentSpec",
    "FileRef",
    "InputSpec",
    "ModelManifest",
    "OutputSpec",
    "ParamsSpec",
    "PostprocessSpec",
    "PreprocessSpec",
    "RunResult",
    "SampleRecord",
    "TargetSpec",
    "TaskSpec",
    "TrainerSpec",
    "ValidationError",
    "compute_sha256_bytes",
    "compute_sha256_file",
    "compute_sha256_str",
    "is_valid_sha256",
    "validate_bbox_coordinates",
    "validate_class_map_against_task",
    "validate_dataset_package",
    "validate_model_package",
    "validate_relative_path",
]
